language: ruby
cache:
  directories:
    - $HOME/.gem/ruby
    - Library/Homebrew/vendor/bundle

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      rvm: system
    - os: linux
      rvm: 2.0.0

before_install:
  - export HOMEBREW_DEVELOPER=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY/Library/Taps";
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      export PATH="$PWD/bin:$PATH";
      umask 022;
    fi

script:
  - brew test-bot

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
