language: c
cache:
  directories:
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
    - $HOME/Library/Homebrew/vendor/bundle
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.2
    - os: linux
      compiler: gcc
      sudo: false

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      MACOS="1";
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY";
    else
      LINUX="1";
      export PATH="$PWD/bin:$PATH";
    fi
  # umask 022 fixes Linux `brew tests` failures;
  - if [ "$LINUX" ]; then
      umask 022;
    fi
  # trigger vendored ruby installation
  - brew help
  - if [ "$MACOS" ]; then
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    fi
  - if [ "$MACOS" ]; then
      travis_retry git -C Library/Taps/homebrew/homebrew-core fetch --depth=1 origin;
    else
      travis_retry git clone --depth=1 https://github.com/Homebrew/homebrew-core Library/Taps/homebrew/homebrew-core;
    fi
  - travis_retry git clone --depth=1 https://github.com/Linuxbrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot

script:
  - brew test-bot

notifications:
  slack:
    secure: NuueXolTjWJDt2Dikv9ZrUdFwgmI04yPlUlfWCDZ2isg9YSV9zACpTJjG4lOBndFeMI89BRgMUNtd6OtvUJOS4jevwJ0BjUwXqVc1GcIta030Y+175UzbvwKDf04b4Dw4pFYvs6b7i8rZOEbWljWesCzeEG5xSr/AgyVm9wmijfQzhYl3eP9sxNbL3tq1XWmSW6sG+t8fgVfXmwGfaq3Kq63bY3YoF5Oj38DpVIxlHpMXOhvyDGNwrwRR3GLTZUENfzPqQaD0+AW4SB1gH3FtBp1aaqSVQHiDV563gEURxPsI+qA7O2TMipM6SjXasTwaHJio1qWjlHuDcU16bxHodS7le8YLpFTVkMYuIncxmD4evQA9YABSj9GSGouOniS6fXCL1YR9fhPAB9AhgzIHxw/+6UyOGIJzSTW3adm19C2joJQN2mX0xl+TxMhdmV+nWq1xGKSiUlWtdT0wrJiuK4tyORPR7rV1owMhwarjcnTxRuNtZQ+OY5VDdZCacPVYe5EmE7R/562dCmUJSPLcj5vSVbne8kmsfIjcpMJrbw19GfxincgocGKBPlaHH8WgQ5SS7w0qxTWZgTAw9LwqE/xgY9VmwcYMupZfE7lXcrz+RSPYojHRgpXL3z3gN4ZNgQSeLOMcTAnhwIR61MnH7WdjNvXaVrdJ2T/RHRwWXc=
  email:
    on_success: never
    on_failure: always
