language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      rvm: system
    - os: linux
      rvm: 2.0.0

before_install:
  - git fetch --tags --unshallow
  - export HOMEBREW_DEVELOPER=1
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      export PATH="$PWD/bin:$PATH";
      umask 022;
    fi

script:
  - brew test-bot

notifications:
  slack:
    secure: NuueXolTjWJDt2Dikv9ZrUdFwgmI04yPlUlfWCDZ2isg9YSV9zACpTJjG4lOBndFeMI89BRgMUNtd6OtvUJOS4jevwJ0BjUwXqVc1GcIta030Y+175UzbvwKDf04b4Dw4pFYvs6b7i8rZOEbWljWesCzeEG5xSr/AgyVm9wmijfQzhYl3eP9sxNbL3tq1XWmSW6sG+t8fgVfXmwGfaq3Kq63bY3YoF5Oj38DpVIxlHpMXOhvyDGNwrwRR3GLTZUENfzPqQaD0+AW4SB1gH3FtBp1aaqSVQHiDV563gEURxPsI+qA7O2TMipM6SjXasTwaHJio1qWjlHuDcU16bxHodS7le8YLpFTVkMYuIncxmD4evQA9YABSj9GSGouOniS6fXCL1YR9fhPAB9AhgzIHxw/+6UyOGIJzSTW3adm19C2joJQN2mX0xl+TxMhdmV+nWq1xGKSiUlWtdT0wrJiuK4tyORPR7rV1owMhwarjcnTxRuNtZQ+OY5VDdZCacPVYe5EmE7R/562dCmUJSPLcj5vSVbne8kmsfIjcpMJrbw19GfxincgocGKBPlaHH8WgQ5SS7w0qxTWZgTAw9LwqE/xgY9VmwcYMupZfE7lXcrz+RSPYojHRgpXL3z3gN4ZNgQSeLOMcTAnhwIR61MnH7WdjNvXaVrdJ2T/RHRwWXc=
  email:
    on_success: never
    on_failure: always
